#
# Your Crowdin credentials
#
'project_id': '1'
'api_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjRlMzAyYTU3Y2QxNTc3OGJmZDUwMTI3ZDZiMDczNmQ0Y2Y2MzUyMjYyMjY2ZjcyYTI5YTM4ZWIzNWZjY2UxZjA4NzZiYzJmMzY1Njk3MmZiIiwiaWF0IjoxNjkwNzQwOTA3Ljk3ODQyMywibmJmIjoxNjkwNzQwOTA3Ljk3ODQyOCwiZXhwIjoxNzIyMjc2OTA3Ljg4Njg4Miwic3ViIjoiMTU5NDI2MjMiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.hhbmAZPgLkx5rjzt40TV868ukotgNeSXlvgplCEK_nlWCjA2VYshcHXZb-HUVvCXX-bD9DnUMlM5srfHYawZjQm2KrjL3H2UYDPJc27B7wibrra3VxpJpuoyloOkIt3NGSAsIgcf93kDapdB1MIFxSKxFuec-CR8rSSHNnSyX1pIKohM54bCQetKM5F5lgabgd_wu2y02HkC53a-jRF9mCBGAL0OdczpHt4nclIgV28GwxJ7MniUC9RKUCuyXQ3BA0VuX0Qtpchx3gcuZAe7_eDd7ho_HIwlgS8s9pvss6ebIK6HlvlL9y3okQ5YAhviEGZ3fmySu_kGY5vz_piPLwWGyG9Ko_EAoQ8HRLL6nVy6ut_kytG8PLXiGIsZilIG6voQmXSAA58IhGaetu422_8tipxHcMczTvP_RlNw4r2dwJ6ivU9azycARqBqGFL0NyDUlGOPr4lYW1F5WbMpmZr72_nc8NoBAkBYNgCAIz9NwAPjVp9CoBoX3gW8Y2-yRxt6ZbkLnXlrKUiVU4IfymO7ZYA1sk4ozlORB8lBLghJDfDy7aM0PslGTxAQ39xXBiJFaqd7vYz8m-sVWbxyiHZYPbTsxE-hDXQzRlGn_00kIAaibi33rw9_LrBGO9N6E73A6jKqOU7c7ab9huGa1pdqjCyshfY-TzwOhfnkKYs'
'base_path': '.'
'base_url': 'https://api.crowdin.com'

#
# Choose file structure in Crowdin
# e.g. true or false
#
'preserve_hierarchy': true

#
# Files configuration
#
files: [
    {
      'source': '/public/locales/en/translation.json', # Source language file pattern
      'translation': '/public/locales/%two_letters_code%/translation.json', # Translation files pattern

      #
      # Files or directories for ignore
      # e.g. ["/**/?.txt", "/**/[0-9].txt", "/**/*\?*.txt"]
      #
      # "ignore": [],

      #
      # The dest allows you to specify a file name in Crowdin
      # e.g. "/messages.json"
      #
      # "dest": "",

      #
      # File type
      # e.g. "json"
      #
      # "type": "",

      #
      # The parameter "update_option" is optional. If it is not set, after the files update the translations for changed strings will be removed. Use to fix typos and for minor changes in the source strings
      # e.g. "update_as_unapproved" or "update_without_changes"
      #
      # "update_option": "",

      #
      # Start block (for XML only)
      #

      #
      # Defines whether to translate tags attributes.
      # e.g. 0 or 1  (Default is 1)
      #
      # "translate_attributes": 1,

      #
      # Defines whether to translate texts placed inside the tags.
      # e.g. 0 or 1 (Default is 1)
      #
      # "translate_content": 1,

      #
      # This is an array of strings, where each item is the XPaths to DOM element that should be imported
      # e.g. ["/content/text", "/content/text[@value]"]
      #
      # "translatable_elements": [],

      #
      # Defines whether to split long texts into smaller text segments
      # e.g. 0 or 1 (Default is 1)
      #
      # "content_segmentation": 1,

      #
      # End block (for XML only)
      #

      #
      # Start .properties block
      #

      #
      # Defines whether single quote should be escaped by another single quote or backslash in exported translations
      # e.g. 0 or 1 or 2 or 3 (Default is 3)
      # 0 - do not escape single quote;
      # 1 - escape single quote by another single quote;
      # 2 - escape single quote by backslash;
      # 3 - escape single quote by another single quote only in strings containing variables ( {0} ).
      #
      # "escape_quotes": 3,

      #
      # Defines whether any special characters (=, :, ! and #) should be escaped by backslash in exported translations.
      # e.g. 0 or 1 (Default is 0)
      # 0 - do not escape special characters
      # 1 - escape special characters by a backslash
      #
      # "escape_special_characters": 0
      #

      #
      # End .properties block
      #

      #
      # Does the first line contain header?
      # e.g. true or false
      #
      # "first_line_contains_header": true,

      #
      # for spreadsheets
      # e.g. "identifier,source_phrase,context,uk,ru,fr"
      #
      # "scheme": "",
    },
  ]
